name: Build releases

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Show system
      run: |
        echo "\e[1;32mCPU:\e[0m"
        lscpu
        cat /proc/cpuinfo
        echo "\e[1;32mMemory:\e[0m"
        free -h
        echo "\e[1;32mStorage:\e[0m"
        df -Th
        echo "\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo "\e[1;32mKernel:\e[0m"
        uname -a

