name: Build releases

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Show system
      run: |
        echo -e "\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\e[1;32mStorage:\e[0m"
        df -Th
        echo -e "\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\e[1;32mKernel:\e[0m"
        uname -a

